### ISSUE TITLE
README.md , Link Demo Loop Ke Halaman Repository :D ? 

### ISSUE THREAD

**Issue by desawarna** [alisyahidin/dash-socmed#1]
Tadi saya kan klik demo ehh loop ke Halaman Repository github projek ini :smile_cat: 
Saran link demo nya pakai github pages :smile_cat: 
[https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)
Btw keren projek nya , :100:

**Comment by desawarna** [comment]
atau pakai Netlify / Surge hi hi

**Comment by alisyahidin** [comment]
sengaja mas, belum saya publish demo nya heheh.
